# Uncomment the next line to define a global platform for your project
target 'homeChef' do
platform :ios, '10.3'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homeChef
 
 pod 'Firebase/Core'
 pod 'Firebase/Auth'
 pod 'Alamofire', '~> 4.5'
 pod 'SwiftyJSON'
end
